import { AlertTriangle } from "lucide-react";

const DisclaimerSection = () => {
  return (
    <section className="py-6 px-6 bg-muted/30 border-t border-border/50">
      <div className="max-w-4xl mx-auto flex items-start gap-3 text-sm text-muted-foreground">
        <AlertTriangle className="w-5 h-5 shrink-0 mt-0.5 text-yellow-500" />
        <p>
          <strong>Disclaimer:</strong> All information provided by BusaAI is generated by AI from different available sources. 
          The data, projections, and recommendations are for informational purposes only and should not be considered as professional 
          financial or legal advice. Please consult qualified professionals before making business decisions.
        </p>
      </div>
    </section>
  );
};

export default DisclaimerSection;
