import { AlertTriangle } from "lucide-react";

const DisclaimerSection = () => {
  return (
    <section className="py-6 px-6 bg-muted/30 border-t border-border/50">
      <div className="max-w-4xl mx-auto flex items-start gap-3 text-sm text-muted-foreground">
        <AlertTriangle className="w-5 h-5 shrink-0 mt-0.5 text-primary" />
        <p>
          <strong>Disclaimer:</strong> Information provided by BusaAI is generated by AI from different available sources.
          Please use it as guidance only and confirm important financial, legal, or business decisions with qualified professionals.
        </p>
      </div>
    </section>
  );
};

export default DisclaimerSection;
